# Generated by Django 5.0.9 on 2024-10-04 22:45

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosOcr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_documento', models.CharField(max_length=18)),
                ('nome_original', models.CharField(max_length=255)),
                ('arquivo', models.CharField(max_length=255)),
                ('extensao_arquivo', models.CharField(max_length=10)),
                ('pasta', models.CharField(max_length=150)),
                ('caminho', models.TextField()),
                ('numero_pagina', models.IntegerField()),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('data_leitura', models.DateTimeField(auto_now_add=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'verbose_name': 'OCR Documentos',
                'verbose_name_plural': 'OCR Documentos',
            },
        ),
        migrations.CreateModel(
            name='DocumentosOcrErros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_documento', models.CharField(max_length=18)),
                ('nome_original', models.CharField(max_length=255)),
                ('arquivo', models.CharField(max_length=255)),
                ('extensao_arquivo', models.CharField(blank=True, max_length=10, null=True)),
                ('pasta', models.CharField(max_length=150)),
                ('caminho', models.TextField()),
                ('numero_pagina', models.IntegerField()),
                ('erro', models.TextField(blank=True, null=True)),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Erros OCR Documentos',
                'verbose_name_plural': 'Erros OCR Documentos',
            },
        ),
        migrations.AddConstraint(
            model_name='documentosocr',
            constraint=models.UniqueConstraint(fields=('id_documento', 'nome_original'), name='unique_id_documento_nome'),
        ),
        migrations.AddConstraint(
            model_name='documentosocrerros',
            constraint=models.UniqueConstraint(fields=('id_documento', 'nome_original'), name='erros_unique_id_documento_nome'),
        ),
    ]
