# Generated by Django 5.0.9 on 2024-09-17 19:33

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_documento', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('caminho_arquivo', models.FilePathField(path='/path/to/save/documents')),
                ('texto_extraido', models.TextField(blank=True, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('ocr', models.BooleanField(default=False)),
            ],
        ),
    ]
