# Generated by Django 5.0.9 on 2024-10-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosocr',
            name='nome_original',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
