# Generated by Django 5.0.9 on 2024-10-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_alter_documentosocr_nome_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosocr',
            name='arquivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentosocr',
            name='caminho',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentosocr',
            name='extensao_arquivo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='documentosocr',
            name='numero_pagina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentosocr',
            name='pasta',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
