# Generated by Django 5.0.9 on 2024-10-09 19:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_alter_documentosocrerros_ano_op_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosocr',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='documentosocr',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ocr_documen_search__995ee4_gin'),
        ),
    ]
