# Generated by Django 5.0.9 on 2024-10-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_documentosocr_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentosocr',
            name='ocr_documen_search__995ee4_gin',
        ),
        migrations.RemoveField(
            model_name='documentosocr',
            name='search_vector',
        ),
    ]
