# Generated by Django 5.0.9 on 2024-10-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_alter_documentosocrerros_arquivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosocr',
            name='search_vector',
        ),
    ]
