# Generated by Django 5.0.9 on 2024-10-10 21:49

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_remove_documentosocr_ocr_documen_search__995ee4_gin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosocr',
            name='ano_op',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Op'),
        ),
        migrations.AlterField(
            model_name='documentosocr',
            name='arquivo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='documentosocr',
            name='caminho',
            field=models.TextField(blank=True, null=True, verbose_name='Caminho'),
        ),
        migrations.AlterField(
            model_name='documentosocr',
            name='conteudo',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='documentosocr',
            name='data_leitura',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Leitura'),
        ),
        migrations.AlterField(
            model_name='documentosocr',
            name='email_usuario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='documentosocr',
            name='extensao_arquivo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Extensão'),
        ),
        migrations.AlterField(
            model_name='documentosocr',
            name='nome_original',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='documentosocr',
            name='num_op',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Num'),
        ),
        migrations.AlterField(
            model_name='documentosocr',
            name='numero_pagina',
            field=models.IntegerField(blank=True, null=True, verbose_name='Página'),
        ),
        migrations.AlterField(
            model_name='documentosocr',
            name='pasta',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Pasta'),
        ),
        migrations.AlterField(
            model_name='documentosocrerros',
            name='ano_op',
            field=models.CharField(blank=True, default='N/A', max_length=6, null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='documentosocrerros',
            name='arquivo',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='documentosocrerros',
            name='data_insercao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inserção'),
        ),
        migrations.AlterField(
            model_name='documentosocrerros',
            name='email_usuario',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='documentosocrerros',
            name='erro',
            field=models.TextField(blank=True, default='N/A', null=True, verbose_name='Erro'),
        ),
        migrations.AlterField(
            model_name='documentosocrerros',
            name='id_documento',
            field=models.CharField(max_length=18, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='documentosocrerros',
            name='num_op',
            field=models.CharField(blank=True, default='N/A', max_length=10, null=True, verbose_name='Op'),
        ),
        migrations.AlterField(
            model_name='documentosocrerros',
            name='numero_pagina',
            field=models.IntegerField(blank=True, default='N/A', null=True, verbose_name='Pasta'),
        ),
    ]
