# Generated by Django 5.0.9 on 2024-10-10 21:56

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_documentosocr_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosocr',
            name='id_documento',
            field=models.CharField(max_length=18, verbose_name='Id'),
        ),
    ]
