# Generated by Django 5.0.9 on 2024-10-23 18:16

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0007_documentosocr_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosocr',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
