# Generated by Django 5.0.9 on 2024-11-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0008_documentosocr_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosocr',
            name='arquivo_existe',
            field=models.BooleanField(blank=True, null=True, verbose_name='Arquivo existe'),
        ),
        migrations.AddField(
            model_name='documentosocrerros',
            name='arquivo_existe',
            field=models.BooleanField(blank=True, null=True, verbose_name='Arquivo existe'),
        ),
    ]
