# Generated by Django 5.0.9 on 2024-11-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0009_documentosocr_arquivo_existe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosocr',
            name='arquivo_existe',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Arquivo existe'),
        ),
        migrations.AlterField(
            model_name='documentosocrerros',
            name='arquivo_existe',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Arquivo existe'),
        ),
    ]
