# Generated by Django 5.0.9 on 2024-12-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0015_logexclusoes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentosocr',
            name='unique_id_documento_nome',
        ),
        migrations.AddConstraint(
            model_name='documentosocr',
            constraint=models.UniqueConstraint(fields=('id_documento', 'data_leitura'), name='unique_id_documento_data_leitura'),
        ),
    ]
